jobs:
  check:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Pull Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./build/main

name: Ci

on:
  schedule:
    - cron: "55 2/3 * * *"
